#!/usr/bin/env python

from setuptools import setup, find_packages

setup(
    name="mkdocs-note",
    version="0.1.0",
    author="Author Name",
    author_email="author@example.com",
    description="A MkDocs plugin to add note boxes to your documentation.",
    long_description=open('README.md').read(),
    long_description_content_type="text/markdown",
    url="https://github.com/virtualguard101/mkdocs-note",
    packages=find_packages(where='src'),
    package_dir={'': 'src'},
    install_requires=[
        "babel==2.17.0",
        "backrefs==5.8",
        "beautifulsoup4==4.13.4",
        "cachecontrol==0.14.0",
        "cairocffi==1.7.1",
        "cairosvg==2.8.2",
        "certifi==2025.4.26",
        "cffi==1.17.1",
        "charset-normalizer==3.4.2",
        "click==8.2.1",
        "colorama==0.4.6",
        "colorlog==6.9.0",
        "coverage==7.10.6",
        "csscompressor==0.9.5",
        "cssselect2==0.8.0",
        "defusedxml==0.7.1",
        "filelock==3.15.4",
        "frontmatter==3.0.8",
        "ghp-import==2.1.0",
        "gitdb==4.0.10",
        "gitpython==3.1.44",
        "griffe==1.9.0",
        "htmlmin2==0.1.13",
        "idna==3.10",
        "iniconfig==2.1.0",
        "jieba==0.42.1",
        "jinja2==3.1.6",
        "jsmin==3.0.1",
        "lxml==6.0.0",
        "markdown==3.8",
        "markdown-callouts==0.4.0",
        "markupsafe==3.0.2",
        "mergedeep==1.3.4",
        "mkdocs==1.6.1",
        "mkdocs-autorefs==1.4.2",
        "mkdocs-drawio==1.11.2",
        "mkdocs-get-deps==0.2.0",
        "mkdocs-git-revision-date-localized-plugin==1.4.7",
        "mkdocs-material==9.6.14",
        "mkdocs-material-extensions==1.3.1",
        "mkdocs-minify-plugin==0.7.1",
        "mkdocs-obsidian-interactive-graph-plugin==0.3.0",
        "mkdocs-redirects==1.2.1",
        "mkdocs-rss-plugin==1.17.3",
        "mkdocstrings==0.30.0",
        "mkdocstrings-python==1.16.12",
        "msgpack==1.0.8",
        "packaging==25.0",
        "paginate==0.5.7",
        "pathspec==0.12.1",
        "pillow==10.4.0",
        "platformdirs==4.3.8",
        "pluggy==1.6.0",
        "pycparser==2.22",
        "pygments==2.19.1",
        "pymdown-extensions==10.15",
        "pypinyin==0.51.0",
        "python-dateutil==2.9.0.post0",
        "pytz==2025.2",
        "pyyaml==5.1",
        "pyyaml-env-tag==1.1",
        "regex==2024.11.6",
        "requests==2.32.3",
        "sgmllib3k==1.0.0",
        "six==1.17.0",
        "smmap==5.0.0",
        "soupsieve==2.7",
        "tinify==1.6.0",
        "tinycss2==1.4.0",
        "typing-extensions==4.14.1",
        "tzdata==2024.1",
        "urllib3==2.4.0",
        "watchdog==6.0.0",
        "webencodings==0.5.1",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: GNU GPLv3 License",
        "Operating System :: OS Independent",
    ],
    entry_points={
        'mkdocs.plugins': [
            'notes = mkdocs_note.plugin:NotesPlugin'
        ]
    },
    python_requires='>=3.12',
)
