## Page tree
nav:
  - index.md
  - Getting Started: getting-started.md

  - User Guide:
    - usage/index.md
    - Installation: usage/installation.md
    - Recent Notes Insertion: usage/recent-notes.md
    - Command Line Interface: usage/cli.md
    - Asset Management: usage/asset-manager.md
    - Network Graph Visualization: usage/network-graph.md
    # - Configuration Options: usage/config.md

  - Contributing Guide:
    - contributing/contributing.md
    - Architecture Overview: contributing/architecture.md
    - Todo List: contributing/todo.md

  - API Reference:
    - references/index.md
    - Frontend or Entry Point:
      - Command Line Interface: references/cli-api.md
      - Plugin Core: references/core-api.md
    - Independent Modules:
      - Plugin Configuration Module: references/config-api.md
      - Network Graph Visualization Module: references/graph-api.md
    - Utils Layers: references/utils-layers.md

  - About:
    - Changelog: about/changelog.md
    - Credits: about/credits.md
    - License: about/license.md

not_in_nav: |
  templates/
